import path from 'node:path';
import fs from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { v2 as cloudinary } from 'cloudinary';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const storageRoot = path.resolve(process.env.MEDIA_STORAGE_DIR || path.join(__dirname, '../storage/media'));
export const MAX_BYTES = 8 * 1024 * 1024;
const allowedFormats = new Set(['jpeg', 'png', 'webp']);

/* Local disk is ephemeral on Render's free tier: every deploy and every
   container restart wipes backend/storage/media while MongoDB keeps pointing
   at the URLs, so admin uploads silently turn into broken images. With
   CLOUDINARY_URL set, uploads go to Cloudinary instead and survive. Without
   it, everything below behaves exactly as it did before — local dev, the
   tests, and any host with a real disk need no configuration. */
export const usingCloudinary = () => Boolean(process.env.CLOUDINARY_URL);
const CLOUDINARY_FOLDER = 'matcha/media';

// The SDK reads CLOUDINARY_URL when configured, so configure on first use
// rather than at import time: tests import this module without loading .env.
let configured = false;
function client() {
  if (!configured) {
    cloudinary.config({ secure: true });
    configured = true;
  }
  return cloudinary;
}

// Both storage backends produce URLs only they hand out, so a URL tells us
// whether the asset is one we manage or a hand-written path in seed data.
export function isManagedUrl(url) {
  return typeof url === 'string' && (url.startsWith('/api/media/files/') || /^https:\/\/res\.cloudinary\.com\//.test(url));
}

export async function prepareImage(buffer) {
  if (!Buffer.isBuffer(buffer) || !buffer.length || buffer.length > MAX_BYTES) {
    throw Object.assign(new Error('กรุณาเลือกรูปขนาดไม่เกิน 8 MB'), { status: 400 });
  }
  try {
    const options = { limitInputPixels: 25_000_000, failOn: 'error' };
    const metadata = await sharp(buffer, options).metadata();
    if (!allowedFormats.has(metadata.format) || (metadata.pages || 1) !== 1) throw new Error('Unsupported image');
    const main = await sharp(buffer, options).rotate().resize({ width: 1600, height: 1600, fit: 'inside', withoutEnlargement: true }).webp({ quality: 85 }).toBuffer({ resolveWithObject: true });
    const thumbnail = await sharp(main.data).resize({ width: 360, height: 360, fit: 'inside', withoutEnlargement: true }).webp({ quality: 80 }).toBuffer();
    return { main: main.data, thumbnail, width: main.info.width, height: main.info.height };
  } catch {
    throw Object.assign(new Error('ไฟล์ไม่ใช่ภาพ JPEG, PNG หรือ WebP ที่รองรับ (สูงสุด 25 ล้านพิกเซล)'), { status: 400 });
  }
}

/* Uploads what sharp already validated and normalised, never the raw upload.
   prepareImage is the security boundary — format allowlist, pixel ceiling, no
   multi-page or SVG payloads — and handing the original buffer to Cloudinary
   instead would give that boundary away for nothing.

   The thumbnail is an eager derivative rather than a second upload: eager
   transformations are generated by us at upload time, so they are delivered
   even with Strict Transformations switched on, and no named transformation
   has to be kept in sync with the dashboard. The main image is delivered
   untransformed for the same reason — it is already 1600px WebP. */
async function uploadToCloudinary(prepared) {
  const result = await new Promise((resolve, reject) => {
    client().uploader.upload_stream({
      folder: CLOUDINARY_FOLDER,
      resource_type: 'image',
      format: 'webp',
      eager: [{ width: 360, height: 360, crop: 'limit', format: 'webp' }]
    }, (error, uploaded) => error ? reject(error) : resolve(uploaded)).end(prepared.main);
  });
  return {
    url: result.secure_url,
    thumbnailUrl: result.eager?.[0]?.secure_url || result.secure_url,
    publicId: result.public_id,
    width: result.width, height: result.height, bytes: result.bytes, mimeType: 'image/webp'
  };
}

async function writeToDisk(prepared, root) {
  const key = randomUUID();
  await fs.mkdir(root, { recursive: true });
  const mainPath = path.join(root, `${key}.webp`);
  const thumbPath = path.join(root, `${key}-thumb.webp`);
  try {
    await fs.writeFile(mainPath, prepared.main, { flag: 'wx' });
    await fs.writeFile(thumbPath, prepared.thumbnail, { flag: 'wx' });
  } catch (error) {
    await Promise.all([mainPath, thumbPath].map(file => fs.unlink(file).catch(() => {})));
    throw error;
  }
  return {
    url: `/api/media/files/${key}.webp`, thumbnailUrl: `/api/media/files/${key}-thumb.webp`,
    publicId: null,
    width: prepared.width, height: prepared.height, bytes: prepared.main.length, mimeType: 'image/webp'
  };
}

export async function storeImage(buffer, root = storageRoot) {
  const prepared = await prepareImage(buffer);
  return usingCloudinary() ? uploadToCloudinary(prepared) : writeToDisk(prepared, root);
}

export async function deleteImage(asset, root = storageRoot) {
  if (!asset) return { success: false, message: 'No asset provided' };

  if (asset.publicId) {
    try {
      const result = await new Promise((resolve, reject) => {
        client().uploader.destroy(asset.publicId, { invalidate: true }, (error, res) => {
          if (error) return reject(error);
          resolve(res);
        });
      });
      if (result?.result !== 'ok' && result?.result !== 'not found') {
        throw new Error(result?.result || 'Cloudinary destroy failed');
      }
      return { success: true, backend: 'cloudinary', result: result?.result };
    } catch (err) {
      const safeMsg = err?.message || 'Storage deletion failed';
      console.warn(`[MediaStorage] Cloudinary destroy failed: ${safeMsg}`);
      throw Object.assign(new Error(safeMsg), { status: 502 });
    }
  }

  // Delete from local disk
  const files = [];
  if (typeof asset.url === 'string' && asset.url.startsWith('/api/media/files/')) {
    files.push(path.join(root, path.basename(asset.url)));
  }
  if (typeof asset.thumbnailUrl === 'string' && asset.thumbnailUrl.startsWith('/api/media/files/')) {
    files.push(path.join(root, path.basename(asset.thumbnailUrl)));
  }

  await Promise.all(
    files.map(file => fs.unlink(file).catch(() => {}))
  );

  return { success: true, backend: 'disk' };
}

export default { storageRoot, MAX_BYTES, usingCloudinary, isManagedUrl, prepareImage, storeImage, deleteImage };
